  name: Java CI

  on:
    push:
      branches:
        - master
    pull_request:
      branches:
        - master
    workflow_dispatch:
      inputs:
        email_to:
          description: 'Email address to send test results'

  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            distribution: 'temurin'
            java-version: '17'


        - name: Install dependencies
          run: mvn clean install -DskipTests


    test:
      runs-on: windows-latest
      needs: build
      if: github.event_name == 'workflow_dispatch'


      steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'

        - name: Run tests
          run: mvn clean install

        - name: Archive test results
          uses: actions/upload-artifact@v3
          with:
            name: test-results
            path: attachments



        - name: Send email
          if: github.event_name == 'workflow_dispatch'  # Ensure this step runs only on manual trigger

          uses: dawidd6/action-send-mail@v3
          with:
            server_address: smtp.gmail.com
            server_port: 465
            username: ${{ secrets.EMAIL_USERNAME }}
            password: ${{ secrets.EMAIL_PASSWORD }}
            subject: "Report for automation suite for booking.com for ${{ github.repository }} ${{ github.sha }}"
            from: Test Suite
            body: |
              Hi,
              The test report for ${{ github.repository }} ${{ github.sha }} has completed.
              Regards.
            to: ${{ github.event.inputs.email_to }}
            attachments:
              attachments/extentReports/*.html
